name: master-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.7.20366.6
    - name: Install dependencies
      run: dotnet restore Tesseract.sln
    - name: Build
      run: dotnet build Tesseract.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test "/tests/HouseofCat.Tests.sln" --no-restore --verbosity normal
