name: nuget-publish

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Manual Publish'
  push:
    branches: [ 'nuget-publish/**' ]
  pull_request:
    branches: [ 'nuget-publish/**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.7.20366.6
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish HouseofCat.Algorithms
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Algorithms/HouseofCat.Algorithms.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Compression
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Compression/HouseofCat.Compression.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Compression.Builtin
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Compression.Builtin/HouseofCat.Compression.Builtin.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Compression.LZ4
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Compression.LZ4/HouseofCat.Compression.LZ4.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Dapper
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Dapper/HouseofCat.Dapper.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Dapper
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Dapper.LegacySqlServer/HouseofCat.Dapper.LegacySqlServer.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Dapper.LegacySqlServer
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Dapper.LegacySqlServer/HouseofCat.Dapper.LegacySqlServer.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Dapper.SqlServer
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Dapper.SqlServer/HouseofCat.Dapper.SqlServer.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Encryption
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Encryption/HouseofCat.Encryption.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Excetions
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Extensions/HouseofCat.Extensions.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Extensions.Host.SerilogSqlServer
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Extensions.Host.SerilogSqlServer/HouseofCat.Extensions.Host.SerilogSqlServer.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Logger
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Logger/HouseofCat.Logger.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.RabbitMQ
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.RabbitMQ/HouseofCat.RabbitMQ.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.RabbitMQ.Client
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.RabbitMQ.Client/HouseofCat.RabbitMQ.Client.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.RabbitMQ.Pipelines
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.RabbitMQ.Pipelines/HouseofCat.RabbitMQ.Pipelines.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.RabbitMQ.Services
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.RabbitMQ.Services/HouseofCat.RabbitMQ.Services.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Reflection
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Reflection/HouseofCat.Reflection.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Utilities
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Utilities/HouseofCat.Utilities.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Workflows
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Workflows/HouseofCat.Workflows.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
    - name: Publish HouseofCat.Workflows.Pipelines
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Workflows.Pipelines/HouseofCat.Workflows.Pipelines.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true